language: node_js
node_js:
  - "0.11"
  - "0.10"

before_install:
  - wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
  - sudo dpkg -i influxdb_latest_amd64.deb
  - sudo service influxdb start
  - npm install -g gulp
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bower install -f
